services:
  gateway:
    build: ./gateway
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
#    volumes:
#      - ./gateway:/app
    networks:
      - medilabo-network

  front:
    build: ./front
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    #      - SERVER_ADDRESS=0.0.0.0
#    volumes:
#      - ./front:/app
    depends_on:
      - gateway
    networks:
      - medilabo-network

  patient:
    build: ./patient
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "9002:9002"
#    volumes:
#      - ./patient:/app
    depends_on:
      - gateway
    networks:
      - medilabo-network

  assessment:
    build: ./assessment
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
#    volumes:
#      - ./assessment:/app
    depends_on:
      - gateway
    networks:
      - medilabo-network

  note:
    build: ./note
    depends_on:
      - note-mongo
      - gateway
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_SERVER: note-mongo
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_URI: mongodb://note-mongo:27017/${MONGO_INITDB_DATABASE}
#      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@note-mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
#    volumes:
#      - ./note:/app
    networks:
      - medilabo-network

  note-mongo:
    build: ./note_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - note_mongo_data:/data/db
    networks:
      - medilabo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@note-mongo:27017/admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - note-mongo
    networks:
      - medilabo-network

volumes:
  note_mongo_data:

networks:
  medilabo-network:
    driver: bridge
